### ISSUE TITLE
See intermediate result

### ISSUE THREAD

**Issue by Praiodan** [mayflower/demockrazy#4]
As admin
I want to see the intermediate result
to be able to see trends and to make a more reliable decision about if I am (already) able to end the votes.

AC: 
GIVEN I have received the admin mail
WHEN I click on the deep link to end my poll
THEN I see the pie chart that is currently shown after ending the vote although vote has not been finished yet.

Use Case:
- If I use the tool not for a decision but for a rough overview of opinions to possibly prepare a decision or just want to measure support, I could decide on end the vote after 80% of the people voted and the result is quite obvious.
- I know intermediate results to my vote and am able to bring those facts to further discussions

**Comment by markus2342** [comment]
Not being able to see intermediate results is a demockrazy design decision.
The objective of demockrazy is to provide voters with the possibility to vote as anonymous and uncontrolled as possible.
Even though the initial intention of the poll creator who enables intermediate results, might be for the benefit of the overall discussion, showing intermediate results yields the possibility of influencing voting decisions.
This risk has to be minimised not by intention, but by design.

**Comment by markus2342** [comment]
Addendum: Closely monitoring intermediate results, physically stalking voters and correlating the activity can result in the exposure of a voters choice. This is especially relevant in the late lifetime of a poll, where new votes are casted sporadically. "Oh, I forgot to vote. I'm going to do that now".
This might be a hopefully never occurring edge case, but when talking about voting it's necessary to preemptively protect the voter.
